export { HomePage } from './HomePage';
export { DashboardPage } from './DashboardPage';
export { SchedinaPage } from './SchedinaPage';
export { ClassificaPage } from './ClassificaPage';
export { RegolamentoPage } from './RegolamentoPage';
export { LoginPage } from './LoginPage';
export { ProfiloPage } from './ProfiloPage';
export { StoricoPage } from './StoricoPage';
export { LivePage } from './LivePage';
